development:
  adapter: postgresql
  encoding: unicode
  database: mypr_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: mypr_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: mypr_production
  pool: 5

